name: Publish MkDocs

on:
  push:
    branches: ["main"]

  workflow_dispatch:  

jobs:    
  build_mkdocs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - run: pip install \
          mkdocs-material     

    - run: mkdocs gh-deploy --config-file mkdocs/mkdocs.yml --force 

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_mkdocs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2    
    
