name: execute

on:
  push:
    branches:
      - 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install fastapi
          pip install uvicorn
          pip install httpx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute tests
        run: |
          echo "111111"
          pwd
          echo "22222"
          pytest tests.py
