name: execute

on:
  push:
    branches:
      - 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install fastapi
          pip install uvicorn
          pip install httpx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install ./commonutils

      - name: Execute tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          echo "111111"
          echo $PYTHONPATH
          echo "22222"
          zip -r lib.zip commonutils
          python -c "import sys; sys.path.append('/home/runner/work/test/test/commonutils.zip')"
          pytest ./api/tests.py
