on:
  pull_request:
    types: [opened, reopened]
      
jobs:
  build_config_service:
    runs-on: ubuntu-latest
    steps:
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: checkout branch
        uses: actions/checkout@v3
      - name: build module
        run: mvn clean install
