on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
      
jobs:
  build_config_service:
    runs-on: ubuntu-latest
    steps:
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: build module
        run: mvn clean install
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
